/* ===================================================
 *  file:       OdrPublicNodes.hh
 * ---------------------------------------------------
 *  purpose:	collection of all pubic node headers
 * ---------------------------------------------------
 *  first edit:	20.11.2005 by M. Dupuis @ VIRES GmbH
 * ===================================================
 */
#ifndef _OPENDRIVE_PUBLIC_NODES_HH
#define _OPENDRIVE_PUBLIC_NODES_HH

// ====== INCLUSIONS ======
#include "OdrBorder.hh"
#include "OdrBridge.hh"
#include "OdrControlEntry.hh"
#include "OdrController.hh"
#include "OdrCornerInertial.hh"
#include "OdrCornerReference.hh"
#include "OdrCornerRelative.hh"
#include "OdrCornerLocal.hh"
#include "OdrCornerRoad.hh"
#include "OdrCrossfall.hh"
#include "OdrDataQuality.hh"
#include "OdrElevation.hh"
#include "OdrErrorDesc.hh"
#include "OdrGeoHeader.hh"
#include "OdrGeoNode.hh"
#include "OdrHeader.hh"
#include "OdrJuncController.hh"
#include "OdrJuncHeader.hh"
#include "OdrJuncLaneLink.hh"
#include "OdrJuncLink.hh"
#include "OdrJuncPriority.hh"
#include "OdrLane.hh"
#include "OdrLaneAccess.hh"
#include "OdrLaneHeight.hh"
#include "OdrLaneRule.hh"
#include "OdrLaneLink.hh"
#include "OdrLaneMaterial.hh"
#include "OdrLaneSection.hh"
#include "OdrLaneSpeed.hh"
#include "OdrLaneValidity.hh"
#include "OdrLaneVisibility.hh"
#include "OdrLaneWidth.hh"
#include "OdrLaneOffset.hh"
#include "OdrMarking.hh"
#include "OdrMarkings.hh"
#include "OdrObject.hh"
#include "OdrObjectOutline.hh"
#include "OdrObjectRef.hh"
#include "OdrObjectMaterial.hh"
#include "OdrOffset.hh"
#include "OdrPositionRoad.hh"
#include "OdrPositionInertial.hh"
#include "OdrRawDataDesc.hh"
#include "OdrReference.hh"
#include "OdrRepeat.hh"
#include "OdrRoadHeader.hh"
#include "OdrRoadLink.hh"
#include "OdrRoadMark.hh"
#include "OdrRoadMarkExplicitLine.hh"
#include "OdrRoadMarkSway.hh"
#include "OdrRoadType.hh"
#include "OdrSignal.hh"
#include "OdrSignalRef.hh"
#include "OdrSignalDep.hh"
#include "OdrSuperelevation.hh"
#include "OdrSurfaceCRG.hh"
#include "OdrTrafficObject.hh"
#include "OdrTunnel.hh"
#include "OdrUserData.hh"
#include "OdrLaneBorder.hh"
#include "OdrRoadSpeed.hh"
#include "OdrGeoReference.hh"
#include "OdrLateralShape.hh"
#include "OdrJuncGroup.hh"
#include "OdrJuncRef.hh"
#include "OdrRoadMarkType.hh"
#include "OdrRoadMarkLine.hh"
#include "OdrParkingSpace.hh"
#include "OdrParkingSpaceMarking.hh"
#include "OdrRailroadSwitch.hh"

#endif /* _OPENDRIVE_PUBLIC_NODES_HH */
